routes/web.php
<?php

use App\Autopart;
use App\LCM;

Route::get('ingresar', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('ingresar', 'Auth\LoginController@login');
Route::post('salir', 'Auth\LoginController@logout')->name('logout');

Route::get('contrasenia/recuperar', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('contrasenia/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('contrasenia/recuperar/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('contrasenia/recuperar', 'Auth\ResetPasswordController@reset')->name('password.update');

Route::get('/', 'AppController@index')->name('home')->middleware('auth');

Route::post('/homologar/empezar', 'HomologarController@empezar');
Route::post('/homologar/finalizar', 'HomologarController@finalizar');

Route::group([
    'middleware' => [
        'auth',
        // 'role:administrador'
    ]
], function () {
    Route::resources([
        'usuarios'     => 'UserController',
        'grupos'       => 'GroupController',
        'perfiles'     => 'RoleController',
        'productos'    => 'ProductController',
        'licencias'    => 'CertificateController',
        'lcms'         => 'LCMController',
        'ncm'          => 'NCMController',
    ]);

    Route::get('/trazas/crear/{tipo}', 'TrazaController@create');
    Route::get('/trazas/{id}/exportar', 'TrazaController@export')->name('trazas.export');
    Route::patch('/trazas/{id}/aprobar', 'TrazaController@aprobar')->name('trazas.aprobar');
    Route::resource('trazas', 'TrazaController')->except(['create']);

    Route::get('/perfil', 'AccountController@index')->name('perfil.index');
    Route::put('/perfil/{usuario}', 'AccountController@update')->name('perfil.update');

    Route::get('/contrasenia/cambiar', 'PasswordController@index')->name('cambiarpassword.index');
    Route::put('/contrasenia/cambiar/{usuario}', 'PasswordController@update')->name('cambiarpassword.update');

    Route::post('/subir/imagenes', 'UploadController@store');
    // Route::post('/importar/licencias', 'ImportController@certificates')->name('import.certificates');
    Route::post('/importar/autopartes', 'ImportController@autoparts')->name('import.autoparts');
    // Route::post('/importar/licencias', 'CertificatesImportController')->name('import.certificates');
    // Route::post('/importar/autopartes', 'AutopartsImportController')->name('import.autoparts');

    Route::post('/importar/cape', 'CAPEImportController')->name('import.cape');
    Route::post('/importar/chas-nacional', 'CHASNacionalImportController')->name('import.chas-nacional');
    Route::post('/importar/chas-extranjera', 'CHASExtranjeraImportController')->name('import.chas-extranjera');
    Route::post('/importar/excepcion-chas', 'ExcepcionCHASImportController')->name('import.excepcion-chas');
    Route::post('/importar/aprobar-chas-extranjera', 'AprobarCHASExtranjeraController')->name('import.aprobar-chas-extranjera');
});

Route::get('{qr}', 'QRInfoController');

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateRoleRequest;
use App\Http\Requests\UpdateRoleRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Spatie\Permission\Models\Permission;
use App\Role;

class RoleController extends Controller
{
    public function index()
    {
        $this->authorize('listar', Role::class);

        $roles = Role::withCount('users')->get();

        return view('perfiles.listado', compact('roles'));
    }

    public function create()
    {
        $this->authorize('crear', Role::class);

        $permissions = Permission::all();

        return view('perfiles.crear', compact('permissions'));
    }

    public function show($id)
    {
        $this->authorize('ver', Role::class);

        $role = $role = Role::findById($id);
        $role->load('permissions');

        return view('perfiles.ver', compact('role'));
    }

    public function edit($id)
    {
        $this->authorize('editar', Role::class);

        $role = Role::findById($id);
        $role->load('permissions');

        $permissions = Permission::all();

        return view('perfiles.editar', compact('role', 'permissions'));
    }

    public function store(CreateRoleRequest $request)
    {
        $this->authorize('crear', Role::class);

        $role = new Role($request->validated());
        $permissions = Permission::find($request->input('permissions', []));

        DB::transaction(function () use ($role, $permissions) {
            $role->save();
            $role->syncPermissions($permissions);
        });

        return redirect()->route('perfiles.index');
    }

    public function update(UpdateRoleRequest $request, $id)
    {
        $this->authorize('editar', Role::class);

        $role = Role::findById($id);
        $role->fill($request->validated());

        $permissions = Permission::find($request->input('permissions', []));

        DB::transaction(function () use ($role, $permissions) {
            $role->save();
            $role->syncPermissions($permissions);
        });

        return redirect()->route('perfiles.index');
    }

    public function destroy($id)
    {
        $this->authorize('eliminar', Role::class);

        $role = Role::findById($id);

        $role->delete();

        return redirect()->route('perfiles.index');
    }
}

resources/views/grupos/crear.blade.php
@extends('layouts.default')

@section('content')
<div class="container-fluid">
  <ol class="breadcrumb">
    <li><a href="{{ route('home') }}">Inicio</a></li>
    <li><a href="{{ route('grupos.index') }}">Grupos de Usuarios</a></li>
    <li class="active">Nuevo</li>
  </ol>

  <h1>
    Nuevo Grupo de Usuarios
  </h1>

  <hr class="my-4">

  <div class="bg-white p-4 mb-4">
    <form action="{{ route('grupos.store') }}" method="post">
      @csrf

      @if ($errors->any())
      <div class="alert alert-danger mx-3 mt-8">
        <h5>Se han producido los siguientes errores:</h5>
        <ol>
          @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
          @endforeach
        </ol>
      </div>
      @endif

      <div class="flex flex-wrap -mx-4">
        <div class="w-1/2 form-group item-form px-4 @error('name') has-error @enderror">
          <label for="name" class="mb-4">Nombre <sup>*</sup></label>
          <input type="text" name="name" class="form-control" required aria-required>
          @error('name')
            <p class="help-block error hidden">{{ $message }}</p>
          @enderror
        </div>

        <div class="w-1/2 form-group item-form px-4 relative @error('active') has-error @enderror">
          <label for="active" class="mb-4">Estado <sup>*</sup></label>
          <select required name="active" class="form-control" id="select-active">
            <option data-placeholder="true"></option>
            <option value="1">Activo</option>
            <option value="0">Inactivo</option>
          </select>
          @error('active')
            <p class="help-block error hidden">{{ $message }}</p>
          @enderror
        </div>

        <div class="w-1/2 form-group item-form px-4 relative">
          <label for="users[]" class="mb-4">Usuarios (Permite seleccionar varios)</label>
          <select multiple name="users[]" class="form-control" id="select-users">
            @foreach ($users as $user)
            <option value="{{ $user->id }}">{{ $user->username }}</option>
            @endforeach
          </select>
        </div>
      </div>

      <div class="flex justify-end">
        <a class="btn btn-success uppercase mr-4 mb-0" href="{{ route('grupos.index') }}">
          Volver
        </a>

        <button class="btn btn-info uppercase mb-0" type="submit">
          Guardar
        </button>
      </div>
    </form>
  </div>
</div>
@endsection

@push('scripts')
<script>
new SlimSelect({
  select: '#select-active',
  placeholder: 'Seleccione el estado',
  showSearch: false,
})

new SlimSelect({
  select: '#select-users',
  placeholder: 'Seleccione los usuarios',
  searchPlaceholder: 'Buscar',
})
</script>
@endpush

resources/views/grupos/editar.blade.php
@extends('layouts.default')

@section('content')
<div class="container-fluid">
  <ol class="breadcrumb">
    <li><a href="{{ route('home') }}">Inicio</a></li>
    <li><a href="{{ route('grupos.index') }}">Grupos de Usuarios</a></li>
    <li class="active">Editar</li>
  </ol>

  <h1>
    Editar grupo <em>{{ $group->name }}</em>
  </h1>

  <hr class="my-4">

  <div class="bg-white p-4 mb-4">
    <form action="{{ route('grupos.update', $group->id) }}" method="post">
      @method('put')
      @csrf

      @if ($errors->any())
      <div class="alert alert-danger mx-3 mt-8">
        <h5>Se han producido los siguientes errores:</h5>
        <ol>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ol>
      </div>
      @endif

      <div class="flex flex-wrap -mx-4">
        <div class="w-1/2 form-group item-form px-4">
          <label for="name" class="mb-4">Nombre <sup>*</sup></label>
          <input type="text" name="name" class="form-control" required aria-required value="{{ old('name', $group->name) }}">
          <p class="help-block error hidden">Ingrese el nombre</p>
        </div>

        <div class="w-1/2 form-group item-form px-4 relative">
          <label for="active" class="mb-4">Estado <sup>*</sup></label>
          <select required name="active" class="form-control" id="select-active">
            <option data-placeholder="true"></option>
            <option value="1" @if (old('active', $group->active) === true) selected @endif>Activo</option>
            <option value="0" @if (old('active', $group->active) === false) selected @endif>Inactivo</option>
          </select>
        </div>

        <div class="w-1/2 form-group item-form px-4 relative">
          <label for="users[]" class="mb-4">Usuarios (Permite seleccionar varios)</label>
          <select multiple name="users[]" class="form-control" id="select-users">
            @foreach ($users as $user)
            <option value="{{ $user->id }}" @if (old('users', $group->users)->contains($user)) selected @endif>{{ $user->username }}</option>
            @endforeach
          </select>
        </div>
      </div>

      <div class="flex justify-end">
        <a class="btn btn-success uppercase mr-4 mb-0" href="{{ route('grupos.index') }}">
          Volver
        </a>

        <button class="btn btn-info uppercase mb-0" type="submit">
          Guardar
        </button>
      </div>
    </form>
  </div>
</div>
@endsection

@push('scripts')
<script>
new SlimSelect({
  select: '#select-active',
  placeholder: 'Seleccione el estado',
  showSearch: false,
})

new SlimSelect({
  select: '#select-users',
  placeholder: 'Seleccione los usuarios',
  searchPlaceholder: 'Buscar',
})
</script>
@endpush

resources/views/grupos/listado.blade.php
@extends('layouts.default')

@section('content')
<div class="container-fluid">
  <ol class="breadcrumb">
    <li><a href="{{ route('home') }}">Inicio</a></li>
    <li class="active">Grupos de Usuarios</li>
  </ol>

  <h1 class="flex justify-between">
    Administrador de Grupo de Usuarios
    @can('crear grupos')
    <a href="{{ route('grupos.create') }}" class="uppercase btn btn-success">
      Nuevo grupo de usuarios
    </a>
    @endcan
  </h1>

  <hr class="my-4">

  <table class="table" id="tabla">
    <thead>
      <tr>
        <td>ID</td>
        <td>NOMBRE DEL GRUPO DE USUARIOS</td>
        <td>USUARIOS</td>
        <td>ACTUALIZADO</td>
        <td>ESTADO</td>
        <th class="text-center"><i class="fa fa-cog"></i></th>
      </tr>
    </thead>

    <tbody>
      @foreach ($groups as $group)
      <tr>
        <td>{{ $group->id }}</td>
        <td>{{ $group->name }}</td>
        <td>{{ $group->users_count }}</td>
        <td>{{ $group->updated_at }}</td>
        <td>{{ $group->active ? 'Activo' : 'Inactivo' }}</td>
        <td class="text-center">
          @can('ver grupos')
          <a href="{{ route('grupos.show', $group->id) }}" class="btn m-0 p-0">
            <i class="fa fa-eye"></i>
          </a>
          @endcan
          @if(!$group->fixed)
            @can('editar grupos')
            <a href="{{ route('grupos.edit', $group->id) }}" class="btn m-0 p-0">
              <i class="fa fa-edit"></i>
            </a>
            @endcan
          @endif
          @if(!$group->fixed)
            @can('eliminar grupos')
              <a
                class="btn m-0 p-0"
                href="{{ route('grupos.destroy', $group->id) }}"
                onclick="confirmDelete(event, {{ $group }})"
              >
                  <i class="fa fa-times"></i>
              </a>
              <form id="delete-form-{{ $group->id }}" action="{{ route('grupos.destroy', $group->id) }}" method="POST" style="display: none;">
                  @csrf
                  @method('delete')
              </form>
              @endcan
            @endif
        </td>
      </tr>
      @endforeach
    </tbody>
  </table>
</div>

@endsection

@push('scripts')
<script>
  $('#tabla').DataTable({
    language: {
      url: 'https://cdn.datatables.net/plug-ins/1.10.19/i18n/Spanish.json'
    }
  })

  function confirmDelete(event, grupo)
  {
    event.preventDefault()
    Swal.fire({
      title: 'Confirmar eliminación',
      html: `Desea eliminar <em>${grupo.name}</em>?`,
      type: 'question',
      showConfirmButton: true,
      showCancelButton: true,
      confirmButtonText: 'Eliminar',
      cancelButtonText: 'Cancelar',
      reverseButtons: true,
      confirmButtonColor: '#0072BB'
    }).then(result => {
      if (result.value) {
        document.getElementById(`delete-form-${grupo.id}`).submit()
      }
    })
  }
</script>
@endpush

resources/views/grupos/ver.blade.php
@extends('layouts.default')

@section('content')
<div class="container-fluid">
  <ol class="breadcrumb">
    <li><a href="{{ route('home') }}">Inicio</a></li>
    <li><a href="{{ route('grupos.index') }}">Grupos de Usuarios</a></li>
    <li class="active">Ver</li>
  </ol>

  <h1>
    Ver grupo <em>{{ $group->name }}</em>
  </h1>

  <hr class="my-4">

  <div class="bg-white p-4 mb-4">
    <div class="flex flex-wrap -mx-4">
      <div class="w-1/2 form-group item-form px-4">
        <label for="name" class="mb-4">Nombre Completo <sup>*</sup></label>
        <input type="text" name="name" class="form-control" readonly value="{{ $group->name }}">
      </div>

      <div class="w-1/2 form-group item-form px-4">
        <label for="name" class="mb-4">Estado <sup>*</sup></label>
        <input readonly type="text" class="form-control" value="{{ $group->active ? 'Activo' : 'Inactivo' }}">
      </div>

      <div class="w-1/2 form-group item-form px-4">
        <label for="name" class="mb-4">Usuarios (Permite seleccionar varios)</label>
        <input readonly type="text" class="form-control" value="{{ $group->users->map->username->implode(', ') }}">
      </div>
    </div>

    <div class="flex justify-end">
      <a class="btn btn-success uppercase mt-4 mb-0" href="{{ route('grupos.index') }}">
        Volver
      </a>
    </div>
  </div>
</div>
@endsection