routes/web.php
<?php

use App\Autopart;
use App\LCM;

Route::get('ingresar', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('ingresar', 'Auth\LoginController@login');
Route::post('salir', 'Auth\LoginController@logout')->name('logout');

Route::get('contrasenia/recuperar', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('contrasenia/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('contrasenia/recuperar/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('contrasenia/recuperar', 'Auth\ResetPasswordController@reset')->name('password.update');

Route::get('/', 'AppController@index')->name('home')->middleware('auth');

Route::post('/homologar/empezar', 'HomologarController@empezar');
Route::post('/homologar/finalizar', 'HomologarController@finalizar');

Route::group([
    'middleware' => [
        'auth',
        // 'role:administrador'
    ]
], function () {
    Route::resources([
        'usuarios'     => 'UserController',
        'grupos'       => 'GroupController',
        'perfiles'     => 'RoleController',
        'productos'    => 'ProductController',
        'licencias'    => 'CertificateController',
        'lcms'         => 'LCMController',
        'ncm'          => 'NCMController',
    ]);

    Route::get('/trazas/crear/{tipo}', 'TrazaController@create');
    Route::get('/trazas/{id}/exportar', 'TrazaController@export')->name('trazas.export');
    Route::patch('/trazas/{id}/aprobar', 'TrazaController@aprobar')->name('trazas.aprobar');
    Route::resource('trazas', 'TrazaController')->except(['create']);

    Route::get('/perfil', 'AccountController@index')->name('perfil.index');
    Route::put('/perfil/{usuario}', 'AccountController@update')->name('perfil.update');

    Route::get('/contrasenia/cambiar', 'PasswordController@index')->name('cambiarpassword.index');
    Route::put('/contrasenia/cambiar/{usuario}', 'PasswordController@update')->name('cambiarpassword.update');

    Route::post('/subir/imagenes', 'UploadController@store');
    // Route::post('/importar/licencias', 'ImportController@certificates')->name('import.certificates');
    Route::post('/importar/autopartes', 'ImportController@autoparts')->name('import.autoparts');
    // Route::post('/importar/licencias', 'CertificatesImportController')->name('import.certificates');
    // Route::post('/importar/autopartes', 'AutopartsImportController')->name('import.autoparts');

    Route::post('/importar/cape', 'CAPEImportController')->name('import.cape');
    Route::post('/importar/chas-nacional', 'CHASNacionalImportController')->name('import.chas-nacional');
    Route::post('/importar/chas-extranjera', 'CHASExtranjeraImportController')->name('import.chas-extranjera');
    Route::post('/importar/excepcion-chas', 'ExcepcionCHASImportController')->name('import.excepcion-chas');
    Route::post('/importar/aprobar-chas-extranjera', 'AprobarCHASExtranjeraController')->name('import.aprobar-chas-extranjera');
});

Route::get('{qr}', 'QRInfoController');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <script src="{{ asset('js/estilos.js') }}"></script>
    <link rel="stylesheet" type="text/css" href="{{ asset('css/estilos.css') }}">
  </head>
  <body class="antialiased">
    <div id="traza">
      <main class="flex min-h-screen">
        @yield('content')
      </main>
    </div>

    {{-- <script src="{{ asset('js/scripts.js') }}"></script> --}}
  </body>
</html>

resources/views/layouts/default.blade.php
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <script>
      window.Laravel = {!! json_encode([
        'csrfToken' => csrf_token(),
      ]) !!};
    </script>

    <script src="{{ asset('js/estilos.js') }}"></script>
    <link rel="stylesheet" type="text/css" href="{{ asset('css/estilos.css') }}">
  </head>
  <body class="antialiased">
    <div class="flex flex-col min-h-screen" id="traza" v-cloak>
      @include('layouts.header')

      <main class="flex-1">
        @yield('content')
      </main>

      @include('layouts.footer')
    </div>

    <script src="{{ asset('js/scripts.js') }}"></script>
    @stack('scripts')
  </body>
</html>

resources/views/layouts/footer.blade.php
<footer class="main-footer">
  <div class="container">
    <div class="row">
      <div class="col-sm-6">
        <a class="navbar-brand" href="#" aria-label="Argentina.gob.ar Presidencia de la Nación">
            <img alt="Argentina.gob.ar" src="{{ asset('images/argentinagob.svg') }}" height="50">
        </a>
      </div>
    </div>
  </div>
</footer>

resources/views/layouts/header.blade.php
<header>
  <nav class="navbar navbar-top navbar-default" role="navigation">
    <div class="container">
      <div class="flex justify-between items-center">
        <div class="navbar-header">
          <a class="navbar-brand" href="{{ route('home') }}" aria-label="Argentina.gob.ar Presidencia de la Nación">
            <img alt="Argentina.gob.ar" src="{{ asset('images/argentinagob.svg') }}" height="50">
          </a>
          @guest
          <a href="{{ route('login') }}" class="btn btn-login btn-link visible-xs m-0">Login</a>
          @endguest
          @auth
          <a
            class="btn btn-login btn-link visible-xs"
            href="{{ route('logout') }}"
            onclick="event.preventDefault(); document.getElementById('logout-form').submit();"
          >
              Logout
          </a>
          @endauth
        </div>
        @guest
        <a href="{{ route('login') }}" class="btn btn-login btn-link hidden-xs m-0">Login</a>
        @endguest
        @auth
        <div class="flex items-center -mx-2">
          @can('listar trazas')
          <a href="{{ route('trazas.index') }}" class="text-celeste uppercase no-underline font-black mr-8">
            Trazas
          </a>
          @endcan

          @can('listar licencias')
          <a href="{{ route('licencias.index') }}" class="text-celeste uppercase no-underline font-black mr-8">
            Licencias
          </a>
          @endcan

          @canany(['listar usuarios', 'listar perfiles', 'listar grupos', 'listar productos', 'listar lcm', 'listar ncm'])
          <div class="dropdown">
            <button class="bg-white text-celeste mr-8 p-0" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fa fa-cog fa-2x"></i>
            </button>
            <ul class="dropdown-menu p-1 right-0" style="left: unset;">
              @can('listar usuarios')<li class="uppercase mb-1"><a href="{{ route('usuarios.index') }}">Usuarios</a></li>@endcan
              @can('listar perfiles')<li class="uppercase my-1"><a href="{{ route('perfiles.index') }}">Perfiles</a></li>@endcan
              @can('listar grupos')<li class="uppercase my-1"><a href="{{ route('grupos.index') }}">Grupos de usuarios</a></li>@endcan
              @can('listar productos')<li class="uppercase my-1"><a href="{{ route('productos.index') }}">Productos (Categorías)</a></li>@endcan
              @can('listar lcms')<li class="uppercase mt-1"><a href="{{ route('lcms.index') }}">LCMs</a></li>@endcan
              @can('listar ncm')<li class="uppercase mt-1"><a href="{{ route('ncm.index') }}">NCM</a></li>@endcan
            </ul>
          </div>
          @endcanany

          <div class="dropdown">
            <button class="bg-white text-celeste p-0" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fa fa-user-circle fa-2x"></i>
            </button>
            <ul class="dropdown-menu p-1 right-0" style="left: unset;">
              <li class="uppercase mb-1"><a href="{{ route('perfil.index') }}">Perfil</a></li>
              <li class="uppercase my-1"><a href="{{ route('cambiarpassword.index') }}">Cambiar contraseña</a></li>
              <li class="uppercase mt-1">
                <a
                  href="{{ route('logout') }}"
                  onclick="event.preventDefault(); document.getElementById('logout-form').submit();"
                >
                    Logout
                </a>
              </li>
            </ul>
          </div>
        </div>

        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
            @csrf
        </form>
        @endauth
      </div>
    </div>
  </nav>
</header>

resources/views/layouts/public-header.blade.php
<header>
  <nav class="navbar navbar-top navbar-default" role="navigation">
    <div class="container">
      <div class="flex justify-between items-center">
        <div class="navbar-header">
          <a class="navbar-brand" href="{{ route('home') }}" aria-label="Argentina.gob.ar Presidencia de la Nación">
            <img alt="Argentina.gob.ar" src="{{ asset('images/argentinagob.svg') }}" height="50">
          </a>
        </div>
      </div>
    </div>
  </nav>
</header>

resources/views/layouts/public.blade.php
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <script src="{{ asset('js/estilos.js') }}"></script>
    <link rel="stylesheet" type="text/css" href="{{ asset('css/estilos.css') }}">
  </head>
  <body class="antialiased">
    <div class="flex flex-col min-h-screen" id="traza" v-cloak>
      @include('layouts.public-header')

      <main class="flex-1">
        @yield('content')
      </main>

      @include('layouts.footer')
    </div>

    <!-- <script src="{{ asset('js/scripts.js') }}"></script> -->
    <!-- @stack('scripts') -->
  </body>
</html>