routes/web.php
<?php

use App\Autopart;
use App\LCM;

Route::get('ingresar', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('ingresar', 'Auth\LoginController@login');
Route::post('salir', 'Auth\LoginController@logout')->name('logout');

Route::get('contrasenia/recuperar', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('contrasenia/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('contrasenia/recuperar/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('contrasenia/recuperar', 'Auth\ResetPasswordController@reset')->name('password.update');

Route::get('/', 'AppController@index')->name('home')->middleware('auth');

Route::post('/homologar/empezar', 'HomologarController@empezar');
Route::post('/homologar/finalizar', 'HomologarController@finalizar');

Route::group([
    'middleware' => [
        'auth',
        // 'role:administrador'
    ]
], function () {
    Route::resources([
        'usuarios'     => 'UserController',
        'grupos'       => 'GroupController',
        'perfiles'     => 'RoleController',
        'productos'    => 'ProductController',
        'licencias'    => 'CertificateController',
        'lcms'         => 'LCMController',
        'ncm'          => 'NCMController',
    ]);

    Route::get('/trazas/crear/{tipo}', 'TrazaController@create');
    Route::get('/trazas/{id}/exportar', 'TrazaController@export')->name('trazas.export');
    Route::patch('/trazas/{id}/aprobar', 'TrazaController@aprobar')->name('trazas.aprobar');
    Route::resource('trazas', 'TrazaController')->except(['create']);

    Route::get('/perfil', 'AccountController@index')->name('perfil.index');
    Route::put('/perfil/{usuario}', 'AccountController@update')->name('perfil.update');

    Route::get('/contrasenia/cambiar', 'PasswordController@index')->name('cambiarpassword.index');
    Route::put('/contrasenia/cambiar/{usuario}', 'PasswordController@update')->name('cambiarpassword.update');

    Route::post('/subir/imagenes', 'UploadController@store');
    // Route::post('/importar/licencias', 'ImportController@certificates')->name('import.certificates');
    Route::post('/importar/autopartes', 'ImportController@autoparts')->name('import.autoparts');
    // Route::post('/importar/licencias', 'CertificatesImportController')->name('import.certificates');
    // Route::post('/importar/autopartes', 'AutopartsImportController')->name('import.autoparts');

    Route::post('/importar/cape', 'CAPEImportController')->name('import.cape');
    Route::post('/importar/chas-nacional', 'CHASNacionalImportController')->name('import.chas-nacional');
    Route::post('/importar/chas-extranjera', 'CHASExtranjeraImportController')->name('import.chas-extranjera');
    Route::post('/importar/excepcion-chas', 'ExcepcionCHASImportController')->name('import.excepcion-chas');
    Route::post('/importar/aprobar-chas-extranjera', 'AprobarCHASExtranjeraController')->name('import.aprobar-chas-extranjera');
});

Route::get('{qr}', 'QRInfoController');

resources/views/usuarios/crear.blade.php
@extends('layouts.default')

@section('content')
<div class="container-fluid">
  <ol class="breadcrumb">
    <li><a href="{{ route('home') }}">Inicio</a></li>
    <li><a href="{{ route('usuarios.index') }}">Usuarios</a></li>
    <li class="active">Nuevo</li>
  </ol>

  <h1>
    Nuevo Usuario
  </h1>

  <hr class="my-4">

  <div class="bg-white p-4 mb-4">
    <form action="{{ route('usuarios.store') }}" method="post">
      @csrf

      @if ($errors->any())
      <div class="alert alert-danger mx-3 mt-8">
        <h5>Se han producido los siguientes errores:</h5>
        <ol>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ol>
      </div>
      @endif

      <div class="flex flex-wrap -mx-2">
        <div class="w-1/2 form-group item-form px-2">
          <label for="name" class="mb-4">Nombre Completo <sup>*</sup></label>
          <input type="text" name="name" class="form-control" required aria-required value="{{ old('name') }}">
          <p class="help-block error hidden">Ingrese el nombre completo</p>
        </div>

        <div class="w-1/2 form-group item-form px-2">
          <label for="username" class="mb-4">Nombre de usuario <sup>*</sup></label>
          <input type="text" name="username" class="form-control" required aria-required value="{{ old('username') }}">
          <p class="help-block error hidden">Ingrese el nombre de usuario</p>
        </div>

        <div class="w-1/2 form-group item-form px-2">
          <label for="email" class="mb-4">Correo Electrónico <sup>*</sup></label>
          <input type="email" name="email" class="form-control" required aria-required value="{{ old('email') }}">
          <p class="help-block error hidden">Ingrese el correo electrónico</p>
        </div>

        <div class="w-1/2 form-group item-form px-2 relative">
          <label for="name" class="mb-4">Estado <sup>*</sup></label>
          <select required name="active" class="form-control" value="{{ old('active') }}" id="select-active">
            <option data-placeholder="true"></option>
            <option value="1">Activo</option>
            <option value="0">Inactivo</option>
          </select>
        </div>

        <div class="w-1/2 form-group item-form px-2">
          <label for="password" class="mb-4">Contraseña <sup>*</sup></label>
          <input type="password" name="password" class="form-control" required aria-required>
          <p class="help-block error hidden">Ingrese la contraseña</p>
        </div>

        <div class="w-1/2 form-group item-form px-2">
          <label for="password_confirmation" class="mb-4">Confirmar contraseña <sup>*</sup></label>
          <input type="password" name="password_confirmation" class="form-control" required aria-required>
          <p class="help-block error hidden">Confirme la contraseña</p>
        </div>

        <div class="w-1/2 form-group item-form px-2 relative">
          <label for="name" class="mb-4">Perfil (Permite seleccionar varios)</label>
          <select required multiple name="roles[]" class="form-control" id="select-roles">
            @foreach ($roles as $role)
            <option class="capitalize" value="{{ $role->id }}">{{ $role->name }}</option>
            @endforeach
          </select>
          <p class="help-block error hidden">Seleccione al menos un perfil</p>
        </div>

        <div class="w-1/2 form-group item-form px-2 relative">
          <label for="name" class="mb-4">Grupo de usuarios (Permite seleccionar varios)</label>
          <select required multiple name="groups[]" class="form-control" id="select-groups">
            @foreach ($groups as $group)
            <option value="{{ $group->id }}">{{ $group->name }}</option>
            @endforeach
          </select>
          <p class="help-block error hidden">Seleccione al menos un grupo</p>
        </div>
      </div>

      <div class="flex justify-end">
        <a class="btn btn-success uppercase mr-4 mb-0" href="{{ route('usuarios.index') }}">
          Volver
        </a>

        <button class="btn btn-info uppercase mb-0" type="submit">
          Guardar
        </button>
      </div>
    </form>
  </div>
</div>
@endsection

@push('scripts')
<script>
new SlimSelect({
  select: '#select-roles',
  placeholder: 'Seleccione los perfiles',
  searchPlaceholder: 'Buscar',
})

new SlimSelect({
  select: '#select-groups',
  placeholder: 'Seleccione los grupos',
  searchPlaceholder: 'Buscar',
})

new SlimSelect({
  select: '#select-active',
  placeholder: 'Seleccione el estado',
  showSearch: false,
})
</script>
@endpush

resources/views/usuarios/editar.blade.php
@extends('layouts.default')

@section('content')
<div class="container-fluid">
  <ol class="breadcrumb">
    <li><a href="{{ route('home') }}">Inicio</a></li>
    <li><a href="{{ route('usuarios.index') }}">Usuarios</a></li>
    <li class="active">Editar</li>
  </ol>

  <h1>
    Editar usuario <em>{{ $user->username }}</em>
  </h1>

  <hr class="my-4">

  <div class="bg-white p-4 mb-4">
    <form action="{{ route('usuarios.update', $user->id) }}" method="post">
      @method('put')
      @csrf

      @if ($errors->any())
      <div class="alert alert-danger mx-3 mt-8">
        <h5>Se han producido los siguientes errores:</h5>
        <ol>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ol>
      </div>
      @endif

      <div class="flex flex-wrap -mx-2">
        <div class="w-1/2 form-group item-form px-2">
          <label for="name" class="mb-4">Nombre Completo <sup>*</sup></label>
          <input type="text" name="name" class="form-control" required aria-required value="{{ $user->name }}">
          <p class="help-block error hidden">Ingrese el nombre completo</p>
        </div>

        <div class="w-1/2 form-group item-form px-2">
          <label for="username" class="mb-4">Nombre de usuario <sup>*</sup></label>
          <input type="text" name="username" class="form-control" required aria-required value="{{ $user->username }}">
          <p class="help-block error hidden">Ingrese el nombre de usuario</p>
        </div>

        <div class="w-1/2 form-group item-form px-2">
          <label for="email" class="mb-4">Correo Electrónico <sup>*</sup></label>
          <input type="email" name="email" class="form-control" required aria-required value="{{ $user->email }}">
          <p class="help-block error hidden">Ingrese el correo electrónico</p>
        </div>

        <div class="w-1/2 form-group item-form px-2 relative">
          <label for="name" class="mb-4">Estado <sup>*</sup></label>
          <select required name="active" class="form-control" id="select-active">
            <option data-placeholder="true"></option>
            <option value="1" @if ($user->active === true) selected @endif>Activo</option>
            <option value="0" @if ($user->active === false) selected @endif>Inactivo</option>
          </select>
        </div>

        <div class="w-1/2 form-group item-form px-2">
          <label for="password" class="mb-4">Contraseña <sup>*</sup></label>
          <input type="password" name="password" class="form-control">
          <p class="help-block error hidden">Ingrese la contraseña</p>
        </div>

        <div class="w-1/2 form-group item-form px-2">
          <label for="password_confirmation" class="mb-4">Confirmar contraseña <sup>*</sup></label>
          <input type="password" name="password_confirmation" class="form-control">
          <p class="help-block error hidden">Confirme la contraseña</p>
        </div>

        <div class="w-1/2 form-group item-form px-2 relative">
          <label for="name" class="mb-4">Perfil (Permite seleccionar varios)</label>
          <select required multiple name="roles[]" class="form-control" id="select-roles">
            @foreach ($roles as $role)
            <option class="capitalize" value="{{ $role->id }}" @if ($user->roles->contains($role)) selected @endif>{{ $role->name }}</option>
            @endforeach
          </select>
          <p class="help-block error hidden">Seleccione al menos un perfil</p>
        </div>

        <div class="w-1/2 form-group item-form px-2 relative">
          <label for="name" class="mb-4">Grupo de usuarios (Permite seleccionar varios)</label>
          <select required multiple name="groups[]" class="form-control" id="select-groups">
            @foreach ($groups as $group)
            <option value="{{ $group->id }}" @if ($user->groups->contains($group)) selected @endif>{{ $group->name }}</option>
            @endforeach
          </select>
          <p class="help-block error hidden">Seleccione al menos un grupo</p>
        </div>
      </div>

      <div class="flex justify-end">
        <a class="btn btn-success uppercase mr-4 mb-0" href="{{ route('usuarios.index') }}">
          Volver
        </a>

        <button class="btn btn-info uppercase mb-0" type="submit">
          Guardar
        </button>
      </div>
    </form>
  </div>
</div>
@endsection

@push('scripts')
<script>
new SlimSelect({
  select: '#select-roles',
  placeholder: 'Seleccione los perfiles',
  searchPlaceholder: 'Buscar',
})

new SlimSelect({
  select: '#select-groups',
  placeholder: 'Seleccione los grupos',
  searchPlaceholder: 'Buscar',
})

new SlimSelect({
  select: '#select-active',
  placeholder: 'Seleccione el estado',
  showSearch: false,
})
</script>
@endpush

resources/views/usuarios/listado.blade.php
@extends('layouts.default')

@section('content')
<div class="container-fluid">
  <ol class="breadcrumb">
    <li><a href="{{ route('home') }}">Inicio</a></li>
    <li class="active">Usuarios</li>
  </ol>

  <h1 class="flex justify-between">
    Administrador de Usuarios
    <a href="{{ route('usuarios.create') }}" class="uppercase btn btn-success">
      Nuevo usuario
    </a>
  </h1>

  <hr class="my-4">

  <table class="table" id="tabla">
    <thead>
      <tr>
        <th>ID</th>
        <th>NOMBRE COMPLETO</th>
        <th>CORREO ELECTRÓNICO</th>
        <th>PERFILES</th>
        <th>GRUPOS</th>
        <th>USUARIO</th>
        <th>ACTUALIZADO</th>
        <th>ESTADO</th>
        <th class="text-center"><i class="fa fa-cog"></i></th>
      </tr>
    </thead>

    <tbody>
      @foreach ($users as $user)
      <tr>
        <td>{{ $user->id }}</td>
        <td>{{ $user->name }}</td>
        <td>{{ $user->email }}</td>
        <td>{{ $user->roles->map->name->implode(', ') }}</td>
        <td>{{ $user->groups->map->name->implode(', ') }}</td>
        <td>{{ $user->username }}</td>
        <td>{{ $user->updated_at }}</td>
        <td>{{ $user->active ? 'Activo' : 'Inactivo' }}</td>
        <td>
          <div class="flex items-center">
            @can('ver usuarios')
            <a href="{{ route('usuarios.show', $user->id) }}" class="mx-2 my-0 p-0">
              <i class="fa fa-eye"></i>
            </a>
            @endcan
            @can('editar usuarios')
            <a href="{{ route('usuarios.edit', $user->id) }}" class="mx-2 my-0 p-0">
              <i class="fa fa-edit"></i>
            </a>
            @endcan
            @can('eliminar usuarios')
            <a
              class="mx-2 my-0 p-0"
              href="{{ route('usuarios.destroy', $user->id) }}"
              onclick="confirmDelete(event, {{ $user }})"
            >
                <i class="fa fa-times"></i>
            </a>
            <form id="delete-form-{{ $user->id }}" action="{{ route('usuarios.destroy', $user->id) }}" method="POST" style="display: none;">
                @csrf
                @method('delete')
            </form>
            @endcan
          </div>
        </td>
      </tr>
      @endforeach
    </tbody>
  </table>
</div>

@endsection

@push('scripts')
<script>
  $('#tabla').DataTable({
    language: {
      url: 'https://cdn.datatables.net/plug-ins/1.10.19/i18n/Spanish.json'
    }
  })

  function confirmDelete(event, user)
  {
    event.preventDefault()
    Swal.fire({
      title: 'Confirmar eliminación',
      html: `Desea eliminar <em>${user.username}</em>?`,
      type: 'question',
      showConfirmButton: true,
      showCancelButton: true,
      confirmButtonText: 'Eliminar',
      cancelButtonText: 'Cancelar',
      reverseButtons: true,
      confirmButtonColor: '#0072BB'
    }).then(result => {
      if (result.value) {
        document.getElementById(`delete-form-${user.id}`).submit()
      }
    })
  }
</script>
@endpush

resources/views/usuarios/ver.blade.php
@extends('layouts.default')

@section('content')
<div class="container-fluid">
  <ol class="breadcrumb">
    <li><a href="{{ route('home') }}">Inicio</a></li>
    <li><a href="{{ route('usuarios.index') }}">Usuarios</a></li>
    <li class="active">Ver</li>
  </ol>

  <h1>
    Ver usuario <em>{{ $user->username }}</em>
  </h1>

  <hr class="my-4">

  <div class="bg-white p-4 mb-4">
    <div class="flex flex-wrap -mx-4">
      <div class="w-1/2 form-group item-form px-4">
        <label for="name" class="mb-4">Nombre Completo <sup>*</sup></label>
        <input readonly type="text" class="form-control" value="{{ $user->name }}">
      </div>

      <div class="w-1/2 form-group item-form px-4">
        <label for="name" class="mb-4">Nombre de usuario <sup>*</sup></label>
        <input readonly type="text" class="form-control" value="{{ $user->username }}">
      </div>

      <div class="w-1/2 form-group item-form px-4">
        <label for="name" class="mb-4">Correo Electrónico <sup>*</sup></label>
        <input readonly type="text" class="form-control" value="{{ $user->email }}">
      </div>

      <div class="w-1/2 form-group item-form px-4">
        <label for="name" class="mb-4">Perfiles </label>
        <input readonly type="text" class="form-control" value="{{ $user->roles->map->name->implode(', ') }}">
      </div>

      <div class="w-1/2 form-group item-form px-4">
        <label for="name" class="mb-4">Estado <sup>*</sup></label>
        <input readonly type="text" class="form-control" value="{{ $user->active ? 'Activo' : 'Inactivo' }}">
      </div>

      <div class="w-1/2 form-group item-form px-4">
        <label for="name" class="mb-4">Grupos de usuarios</label>
        <input readonly type="text" class="form-control" value="{{ $user->groups->map->name->implode(', ') }}">
      </div>
    </div>

    <div class="flex justify-end">
      <a class="btn btn-success uppercase mb-0" href="{{ route('usuarios.index') }}">
        Volver
      </a>
    </div>
  </div>
</div>
@endsection