routes/web.php
<?php

use App\Autopart;
use App\LCM;

Route::get('ingresar', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('ingresar', 'Auth\LoginController@login');
Route::post('salir', 'Auth\LoginController@logout')->name('logout');

Route::get('contrasenia/recuperar', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('contrasenia/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('contrasenia/recuperar/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('contrasenia/recuperar', 'Auth\ResetPasswordController@reset')->name('password.update');

Route::get('/', 'AppController@index')->name('home')->middleware('auth');

Route::post('/homologar/empezar', 'HomologarController@empezar');
Route::post('/homologar/finalizar', 'HomologarController@finalizar');

Route::group([
    'middleware' => [
        'auth',
        // 'role:administrador'
    ]
], function () {
    Route::resources([
        'usuarios'     => 'UserController',
        'grupos'       => 'GroupController',
        'perfiles'     => 'RoleController',
        'productos'    => 'ProductController',
        'licencias'    => 'CertificateController',
        'lcms'         => 'LCMController',
        'ncm'          => 'NCMController',
    ]);

    Route::get('/trazas/crear/{tipo}', 'TrazaController@create');
    Route::get('/trazas/{id}/exportar', 'TrazaController@export')->name('trazas.export');
    Route::patch('/trazas/{id}/aprobar', 'TrazaController@aprobar')->name('trazas.aprobar');
    Route::resource('trazas', 'TrazaController')->except(['create']);

    Route::get('/perfil', 'AccountController@index')->name('perfil.index');
    Route::put('/perfil/{usuario}', 'AccountController@update')->name('perfil.update');

    Route::get('/contrasenia/cambiar', 'PasswordController@index')->name('cambiarpassword.index');
    Route::put('/contrasenia/cambiar/{usuario}', 'PasswordController@update')->name('cambiarpassword.update');

    Route::post('/subir/imagenes', 'UploadController@store');
    // Route::post('/importar/licencias', 'ImportController@certificates')->name('import.certificates');
    Route::post('/importar/autopartes', 'ImportController@autoparts')->name('import.autoparts');
    // Route::post('/importar/licencias', 'CertificatesImportController')->name('import.certificates');
    // Route::post('/importar/autopartes', 'AutopartsImportController')->name('import.autoparts');

    Route::post('/importar/cape', 'CAPEImportController')->name('import.cape');
    Route::post('/importar/chas-nacional', 'CHASNacionalImportController')->name('import.chas-nacional');
    Route::post('/importar/chas-extranjera', 'CHASExtranjeraImportController')->name('import.chas-extranjera');
    Route::post('/importar/excepcion-chas', 'ExcepcionCHASImportController')->name('import.excepcion-chas');
    Route::post('/importar/aprobar-chas-extranjera', 'AprobarCHASExtranjeraController')->name('import.aprobar-chas-extranjera');
});

Route::get('{qr}', 'QRInfoController');

app/Traza.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Traza extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'type',
        'number',
        'user',
        'division',
        'sector',
        'tag',
        'validation',
        'signature',
        'auth_level',
    ];

    protected $casts = [
        'files' => 'array'
    ];

    public function lcms()
    {
        return $this->hasMany(LCM::class);
    }

    public function autoparts()
    {
        return $this->hasMany(Autopart::class);
    }

    public function items()
    {
        switch ($this->type) {
            case 'chas':
            case 'excepcion-chas':
                return $this->autoparts();
            break;
            case 'cape':
                return $this->lcms();
            break;
        }
    }

    public function getApprovedAttribute()
    {
        if ($this->autoparts->every->hasCHAS()) return true;

        return false;
    }
}

app/Http/Controllers/TrazaController.php
<?php

namespace App\Http\Controllers;

use App\Autopart;
use App\Http\Requests\AprobarTrazaRequest;
use App\Http\Requests\CreateTrazaRequest;
use App\LCM;
use App\NCM;
use App\Product;
use App\Traza;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class TrazaController extends Controller
{
    public function index()
    {
        $this->authorize('listar', Traza::class);

        $trazas = Traza::all();

        return view('trazas.listado', compact('trazas'));
    }

    public function show($id)
    {
        $this->authorize('ver', Traza::class);

        $traza = Traza::findOrFail($id);

        return view('trazas.ver', compact('traza'));
    }

    public function create($type)
    {
        $this->authorize('crear', Traza::class);

        if (!in_array($type, ['chas', 'cape', 'excepcion-chas'])) abort(404);

        return view('trazas.crear', compact('type'));
    }

    public function store(CreateTrazaRequest $request)
    {
        $this->authorize('crear', Traza::class);

        $traza = new Traza($request->validated());
        $uuid = Str::uuid();
        $traza->uuid = $uuid;

        // todo: mejorar esto
        $files = [];

        foreach($request->documents as $key => $field) {
            if (is_array($field)) { // puede haber varios archivos del mismo tipo: documents[foto][$i]
                foreach($field as $file) {
                    $savedName = $file->store('documents/' . $uuid, 'public');
                    $fileData = [
                        'name' => $file->getClientOriginalName(),
                        'file' => $savedName,
                        'type' => $key
                    ];
                    array_push($files, $fileData);
                }
            } else {
                $savedName = $field->store('documents/' . $uuid, 'public');
                $fileData = [
                    'name' => $field->getClientOriginalName(),
                    'file' => $savedName,
                    'type' => $key
                ];
                array_push($files, $fileData);
            }
        }

        $traza->files = $files;
        // esto

        DB::transaction(function () use ($request, $traza) {
            $traza->save();

            switch ($request->type) {
                case 'cape':
                    foreach ($request->lcms as $lcm) {
                        $matchedLcm = LCM::where('number', $lcm['lcm'])
                            ->where('brand', $lcm['brand'])
                            ->where('model', $lcm['model'])
                            ->where('origin', $lcm['origin'])
                            ->whereNull('cape')
                            ->first();

                        $matchedLcm->generarCAPE($lcm['product']);
                        $matchedLcm->traza()->associate($traza);
                        $matchedLcm->pictures = explode(',', $lcm['pictures']);

                        $matchedLcm->save();
                    }
                break;
                case 'chas':
                    if (empty($request->documents['wp29'])) {
                        // nacional
                        foreach ($request->autoparts as $autopart) {
                            $matchedAutopart = Autopart::where('brand', $autopart['brand'])
                                ->where('model', $autopart['model'])
                                ->where('origin', $autopart['origin'])
                                ->whereNull('chas')
                                ->first();

                            $matchedAutopart->generarChas('nac');
                            $matchedAutopart->traza()->associate($traza);
                            $matchedAutopart->pictures = explode(',', $autopart['pictures']);
                            $matchedAutopart->save();

                            $matchedAutopart->certificate->traza()->associate($traza);
                            $matchedAutopart->certificate->save();
                        }
                    } else {
                        // extranjero
                        foreach ($request->autoparts as $autopart) {
                            $newAutopart = new Autopart($autopart);
                            $newAutopart->traza()->associate($traza);
                            $newAutopart->pictures = explode(',', $autopart['pictures']);

                            $category = implode('.', array_filter([$autopart['product'], $autopart['family']]));
                            $product = Product::findByCategory($category);
                            $newAutopart->product()->associate($product);

                            $ncm = NCM::findByCategory($autopart['ncm']);
                            $newAutopart->ncm()->associate($ncm);

                            $newAutopart->save();
                        }
                    }
                break;
                case 'excepcion-chas':
                    foreach ($request->autoparts as $autopart) {
                        $newAutopart = new Autopart($autopart);
                        $newAutopart->traza()->associate($traza);
                        $newAutopart->pictures = explode(',', $autopart['pictures']);

                        $category = implode('.', array_filter([$autopart['product'], $autopart['family']]));
                        $product = Product::findByCategory($category);
                        $newAutopart->product()->associate($product);

                        $ncm = NCM::findByCategory($autopart['ncm']);
                        $newAutopart->ncm()->associate($ncm);

                        $newAutopart->generarChas('nac');

                        $newAutopart->save();
                    }
                break;
            }
        });

        return redirect()->route('trazas.index');
    }

    public function destroy($id)
    {
        $this->authorize('eliminar', Traza::class);

        $traza = Traza::findOrFail($id);

        $traza->delete();

        return redirect()->route('trazas.index');
    }

    public function export($id)
    {
        $this->authorize('exportar', Traza::class);

        $traza = Traza::findOrFail($id);

        if ($traza->items->isNotEmpty()) {
            if (file_exists("{$traza->number}.zip")) unlink("{$traza->number}.zip");
            $zip = new \ZipArchive;
            $zip->open("{$traza->number}.zip", \ZipArchive::CREATE);

            foreach ($traza->items as $item) {
                $name = $item instanceof Autopart ? $item->chas : $item->cape;
                $zip->addFromString("{$traza->number}/$name.png", $item->qr);
            }

            $zip->close();

            return response()->download("{$traza->number}.zip");
        }

        abort(404);
    }

    // esto por ahora acá
    public function aprobar(AprobarTrazaRequest $request, $id)
    {
        $this->authorize('crear', Traza::class);

        $traza = Traza::findOrFail($id);

        foreach ($request->autoparts as $autopart) {
            $matchedAutopart = Autopart::where('brand', $autopart['brand'])
                ->where('model', $autopart['model'])
                ->where('origin', $autopart['origin'])
                ->whereNull('chas')
                ->first();

            $matchedAutopart->generarCHAS('ext');
            $matchedAutopart->save();
        }
    }
}

resources/views/trazas/listado.blade.php
@extends('layouts.default')

@section('content')
<div class="container-fluid">
  <ol class="breadcrumb">
    <li><a href="{{ route('home') }}">Inicio</a></li>
    <li class="active">Trazas</li>
  </ol>

  <h1 class="flex justify-between">
    Trazas
    <div class="flex">
      @can('crear trazas')
      <div class="dropdown">
        <button
          class="uppercase btn btn-success"
          data-target="#"
          data-toggle="dropdown"
          role="button"
        >
          Nueva traza
        </button>
        <ul class="p-1 dropdown-menu left-auto right-0">
          <li class="text-right">
            <a href="{{ url('/trazas/crear/chas') }}" class="uppercase">
              Solicitud de Certificación de Homologación de Autopartes y/o Elementos de Seguridad
            </a>
          </li>
          <li class="text-right">
            <a href="{{ url('/trazas/crear/cape') }}" class="uppercase">
              Solicitud del Certificado de Autoparte Primer Equipo (CAPE) - Excepción CHAS
            </a>
          </li>
          <li class="text-right">
            <a href="{{ url('/trazas/crear/excepcion-chas') }}" class="uppercase mb-0">
              Solicitud de Excepción CHAS
            </a>
          </li>
        </ul>
      </div>
      @endcan
      {{-- @can('exportar trazas')
      <button type="button" class="btn btn-success uppercase mx-2" onclick="exportarTrazas()">
        Exportar Excel
      </button>
      @endcan --}}
    </div>
  </h1>

  <hr class="my-4">

  <table class="table" id="tabla">
    <thead>
      <tr>
        <td>ID</td>
        <td>TIPO</td>
        <td>NÚMERO</td>
        <td>CREADO</td>
        <th class="text-center"><i class="fa fa-cog"></i></th>
      </tr>
    </thead>

    <tbody>
      @foreach ($trazas as $traza)
      <tr>
        <td>{{ $traza->id }}</td>
        <td>{{ __('traza.' . $traza->type) }}</td>
        <td>{{ $traza->number }}</td>
        <td>{{ $traza->created_at }}</td>
        <td class="text-center">
          @can('ver trazas')
            <a href="{{ route('trazas.show', $traza->id) }}" class="btn m-0 p-0">
              <i class="fa fa-eye"></i>
            </a>
          @endcan
          @if ($traza->items->isNotEmpty())
            @can('exportar trazas')
              <a href="{{ route('trazas.export', $traza->id) }}" class="btn m-0 p-0 text-azul hover:text-black">
                <i class="fa fa-download"></i>
              </a>
            @endcan
          @endif
          @can('eliminar trazas')
            <a
              class="btn my-0 p-0"
              href="{{ route('trazas.destroy', $traza->id) }}"
              onclick="confirmDelete(event, {{ $traza }})"
            >
                <i class="fa fa-times"></i>
            </a>
            <form id="delete-form-{{ $traza->id }}" action="{{ route('trazas.destroy', $traza->id) }}" method="POST" style="display: none;">
                @csrf
                @method('delete')
            </form>
          @endcan
        </td>
      </tr>
      @endforeach
    </tbody>
  </table>
</div>

@endsection

@push('scripts')
<script>
  $('#tabla').DataTable({
    language: {
      url: 'https://cdn.datatables.net/plug-ins/1.10.19/i18n/Spanish.json',
    },
    order: [[ 0, 'desc' ]]
  })

  function exportarTrazas () {
    Swal.fire({
      type: 'info',
      text: 'En construcción'
    })
  }

  function confirmDelete(event, traza)
  {
    event.preventDefault()
    Swal.fire({
      title: 'Confirmar eliminación',
      html: `Desea eliminar <em>${traza.number}</em>?`,
      type: 'question',
      showConfirmButton: true,
      showCancelButton: true,
      confirmButtonText: 'Eliminar',
      cancelButtonText: 'Cancelar',
      reverseButtons: true,
      confirmButtonColor: '#0072BB'
    }).then(result => {
      if (result.value) {
        document.getElementById(`delete-form-${traza.id}`).submit()
      }
    })
  }
</script>
@endpush

resources/views/trazas/ver.blade.php
@extends('layouts.default')

@section('content')
<traza-form
  inline-template
  :traza="{{ $traza }}"
>
  <div class="container-fluid">
    <ol class="breadcrumb">
      <li><a href="{{ route('home') }}">Inicio</a></li>
      <li><a href="{{ route('trazas.index') }}">Trazas</a></li>
      <li class="active">Ver</li>
    </ol>

    <h1 class="flex justify-between">
      <span>
        Ver traza <em>{{ $traza->number }}</em>
      </span>

      @if ($traza->type === 'chas' && !$traza->approved)
      <div class="dropdown">
        <button
          class="uppercase btn btn-success"
          data-target="#"
          data-toggle="dropdown"
          role="button"
        >
          Aprobar licencias
        </button>
        <ul class="p-1 dropdown-menu left-auto right-0">
          <li>
            <label class="text-base">
              Seleccionar archivo
            </label>
            <importer
              accept=".csv, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel"
              endpoint="{{ route('import.aprobar-chas-extranjera') }}"
              @valid="data => (aprobar = data, excel = true, showApprovalConfirmation())"
            >
            </importer>
            {{-- <form
              action="{{ route('trazas.aprobar', $traza->id) }}"
              v-if="excel && aprobar.length > 0"
              class="text-center"
            >
              <formalizer
                name="autopartes"
                :data="aprobar"
              >
              </formalizer>
              <button class="btn btn-primary mt-2">
                Confirmar
              </button>
            </form> --}}
          </li>
        </ul>
      </div>
      @endif
    </h1>

    <hr class="my-4">

    <div class="bg-white p-4 mb-4">
      <div class="flex flex-wrap -mx-4">
        <div class="w-1/2 form-group item-form px-4 @error('number') has-error @enderror">
            <label for="number" class="mb-4">Número de TAD <sup>*</sup></label>
            <input readonly value="{{ $traza->number }}" type="text" class="form-control">
            @error('number')
              <p class="help-block error hidden">{{ $message }}</p>
            @enderror
          </div>

          <div class="w-1/2 form-group item-form px-4 @error('user') has-error @enderror">
            <label for="user" class="mb-4">Usuario iniciador <sup>*</sup></label>
            <input readonly value="{{ $traza->user }}" type="text" class="form-control">
            @error('user')
              <p class="help-block error hidden">{{ $message }}</p>
            @enderror
          </div>

          <div class="w-1/2 form-group item-form px-4 @error('division') has-error @enderror">
            <label for="division" class="mb-4">Repartición iniciadora <sup>*</sup></label>
            <input readonly value="{{ $traza->division }}" type="text" class="form-control">
            @error('division')
              <p class="help-block error hidden">{{ $message }}</p>
            @enderror
          </div>

          <div class="w-1/2 form-group item-form px-4 @error('sector') has-error @enderror">
            <label for="sector" class="mb-4">Sector iniciador <sup>*</sup></label>
            <input readonly value="{{ $traza->sector }}" type="text" class="form-control">
            @error('sector')
              <p class="help-block error hidden">{{ $message }}</p>
            @enderror
          </div>

          <div class="w-1/2 form-group item-form px-4 @error('tag') has-error @enderror">
            <label for="tag" class="mb-4">Etiqueta <sup>*</sup></label>
            <input readonly value="{{ $traza->tag }}" type="text" class="form-control">
            @error('tag')
              <p class="help-block error hidden">{{ $message }}</p>
            @enderror
          </div>

          <div class="w-1/2 form-group item-form px-4 @error('validation') has-error @enderror">
            <label for="validation" class="mb-4">Validación inicial <sup>*</sup></label>
            <input readonly value="{{ $traza->validation }}" type="text" class="form-control">
            @error('validation')
              <p class="help-block error hidden">{{ $message }}</p>
            @enderror
          </div>

          <div class="w-1/2 form-group item-form px-4 relative @error('signature') has-error @enderror">
            <label for="signature" class="mb-4">Firma conjunta <sup>*</sup></label>
            <input readonly value="{{ $traza->signature ? 'Si' : 'No' }}" type="text" class="form-control">
            @error('signature')
              <p class="help-block error hidden">{{ $message }}</p>
            @enderror
          </div>

          <div class="w-1/2 form-group item-form px-4 @error('auth_level') has-error @enderror">
            <label for="auth_level" class="mb-4">Nivel de autenticación <sup>*</sup></label>
            <input readonly value="{{ $traza->auth_level }}" type="text" class="form-control">
            @error('auth_level')
              <p class="help-block error hidden">{{ $message }}</p>
            @enderror
          </div>
      </div>

      @switch($traza->type)
        @case('chas')
        @case('excepcion-chas')
          @if($traza->autoparts->isNotEmpty())
            <h3>
              Autopartes
            </h3>
            <div class="flex flex-wrap">
              @foreach ($traza->autoparts as $autopart)
              <div class="flex items-center justify-center w-1/2">
                <p>
                  {{ $autopart->brand }} {{ $autopart->model }} {{ $autopart->origin }} @if($autopart->chas)<span class="text-verde font-bold">{{ $autopart->chas }}</span>
                </p>
                <img src="data:image/png;base64,{{ base64_encode($autopart->qr) }}">@endif
              </div>
              @endforeach
            </div>
          @endif
        @break

        @case('cape')
          @if($traza->lcms->isNotEmpty())
            <h3>
              Autopartes
            </h3>
            <div class="flex flex-wrap">
              @foreach ($traza->lcms as $lcm)
              <div class="flex items-center justify-center w-1/2">
                <p>
                  {{ $lcm->brand }} {{$lcm->model}} {{$lcm->country}} @if($lcm->cape)<span class="text-verde font-bold">{{$lcm->cape}}</span>
                </p>
                <img src="data:image/png;base64,{{ base64_encode($lcm->qr) }}">@endif
              </div>
              @endforeach
            </div>
          @endif
        @break
      @endswitch

      <h3>
        Documentos
      </h3>

      <div class="flex flex-wrap -mx-4">
        @foreach($traza->files as $file)
          <div class="w-full px-4">
            <a href="{{ Storage::url($file['file']) }}" download="{{ $file['name'] }}">
              @lang('traza.' . $file['type'])
            </a>
          </div>
        @endforeach
      </div>

      <div class="flex justify-end">
        <a class="btn btn-success uppercase mr-4 mb-0" href="{{ route('trazas.index') }}">
          Volver
        </a>
      </div>
    </div>
  </div>
</traza-form>
@endsection